inherit_gem:
  datarockets-style:
    - config/rails.yml

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Lint/Debugger:
  Exclude:
    - 'app/events/base_event.rb'

Naming/MemoizedInstanceVariableName:
  Exclude: 
    - 'oauth_stragety.rb'